/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author nicolas
 */
public class ConversorVelocidad extends javax.swing.JFrame {

    /**
     * Creates new form TallaCalzado
     */
    int xMouse, yMouse;

    public ConversorVelocidad() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        velocidadField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cmb1 = new javax.swing.JComboBox<>();
        cmb2 = new javax.swing.JComboBox<>();
        convertirBtn = new javax.swing.JPanel();
        convertirTxt = new javax.swing.JLabel();
        result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                headerMouseReleased(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Velocidad");

        velocidadField.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        velocidadField.setForeground(new java.awt.Color(39, 103, 255));
        velocidadField.setBorder(null);
        velocidadField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                velocidadFieldMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(39, 103, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        cmb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km/s", "m/s", "km/h", "Milla por hora (mph)" }));
        cmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb1ActionPerformed(evt);
            }
        });

        cmb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m/s", "km/s", "km/h", "Milla por hora (mph)" }));
        cmb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb2ActionPerformed(evt);
            }
        });

        convertirBtn.setBackground(new java.awt.Color(39, 103, 255));
        convertirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convertirBtnMouseClicked(evt);
            }
        });

        convertirTxt.setBackground(new java.awt.Color(255, 255, 255));
        convertirTxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        convertirTxt.setForeground(new java.awt.Color(255, 255, 255));
        convertirTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        convertirTxt.setText("Convertir");
        convertirTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout convertirBtnLayout = new javax.swing.GroupLayout(convertirBtn);
        convertirBtn.setLayout(convertirBtnLayout);
        convertirBtnLayout.setHorizontalGroup(
            convertirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(convertirTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        convertirBtnLayout.setVerticalGroup(
            convertirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(convertirTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        result.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        result.setForeground(new java.awt.Color(39, 103, 255));
        result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmb1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(velocidadField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb2, javax.swing.GroupLayout.Alignment.TRAILING, 0, 244, Short.MAX_VALUE)
                    .addComponent(convertirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(velocidadField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmb1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(convertirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 290, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "¿Desea Elegir otro conversor?");
        // 0=yes, 1=no, 2=cancel
        System.out.println(input);
        if (input == 0) {
            this.setVisible(false);

            MenuPrincipal mp = new MenuPrincipal();
            mp.setVisible(true);

            JOptionPane.showMessageDialog(null, "Programa Finalizado");
        } else if (input == 1) {
            JOptionPane.showMessageDialog(null, "Programa Finalizado");
            System.exit(0);
        }
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        // TODO add your handling code here:
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        // TODO add your handling code here:
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_headerMouseReleased

    private void cmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb1ActionPerformed

    private void cmb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb2ActionPerformed

    private void convertirBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertirBtnMouseClicked
        // TODO add your handling code here:
        double resultado;
        try {
            if (this.velocidadField.getText().isEmpty() && this.velocidadField.getText().matches("[+-]?\\d*(\\.\\d+)?")) {
                this.result.setText("Debe ingresar un valor valido");
            } else {
                if (this.cmb1.getSelectedItem() == this.cmb2.getSelectedItem()) {
                    this.result.setText("Seleccione otra velocidad");
                } else {
                    // KM/S -> M/S / M/S -> KM/S
                    if (this.cmb1.getSelectedIndex() == 0 && this.cmb1.getSelectedIndex() == 0) {
                        resultado = Double.parseDouble(this.velocidadField.getText()) * 1000;
                        this.result.setText(String.valueOf(resultado) + " m/s");
                    } else if (this.cmb1.getSelectedIndex() == 1 && this.cmb2.getSelectedIndex() == 1) {
                        resultado = Double.parseDouble(this.velocidadField.getText()) / 1000;
                        this.result.setText(String.valueOf(resultado) + " km/s");
                    }
                    // KM/S -> KM/H / KM/H -> KM/S
                    if (this.cmb1.getSelectedIndex() == 0 && this.cmb2.getSelectedIndex() == 2) {
                        resultado = Double.parseDouble(this.velocidadField.getText()) * 3600;
                        this.result.setText(String.valueOf(resultado) + " km/h");
                    } else if(this.cmb1.getSelectedIndex() == 2 && this.cmb2.getSelectedIndex() == 1) {
                        resultado = Double.parseDouble(this.velocidadField.getText()) / 3600;
                        System.out.println(resultado);
                        this.result.setText(String.valueOf(resultado) + " km/s");
                    }
                    // KM/S -> MPH / MPH -> KM/S
                    if(this.cmb1.getSelectedIndex() == 0 && this.cmb2.getSelectedIndex() == 3) {
                        resultado = Double.parseDouble(this.velocidadField.getText()) * 2237;
                        this.result.setText(String.valueOf(resultado) + " mph");
                    } else if(this.cmb1.getSelectedIndex() == 3 && this.cmb2.getSelectedIndex() == 1) {
                        resultado = Double.parseDouble(this.velocidadField.getText()) / 2237;
                        this.result.setText(String.valueOf(resultado) + " km/s");
                    }
                    // M/S -> KM/H / KM/H -> M/S
                    if(this.cmb1.getSelectedIndex() == 1 && this.cmb2.getSelectedIndex() == 2) {
                        resultado = Double.parseDouble(this.velocidadField.getText()) * 3.6;
                        this.result.setText(String.valueOf(resultado) + " km/h");
                    } else if(this.cmb1.getSelectedIndex() == 2 && this.cmb2.getSelectedIndex() == 0) {
                        resultado = Double.parseDouble(this.velocidadField.getText()) / 3.6;
                        this.result.setText(String.valueOf(resultado) + " m/s");
                    }
                    // M/S -> MPH / MPH -> M/S
                    if(this.cmb1.getSelectedIndex() == 1 && this.cmb2.getSelectedIndex() == 3) {
                        resultado = Double.parseDouble(this.velocidadField.getText()) * 2237;
                        this.result.setText(String.valueOf(resultado) + " mph");
                    } else if(this.cmb1.getSelectedIndex() == 3 && this.cmb2.getSelectedIndex() == 0) {
                        resultado = Double.parseDouble(this.velocidadField.getText()) / 2237;
                        this.result.setText(String.valueOf(resultado) + " m/s");
                    }
                    // KM/H -> MPH / MPH -> KM/H
                    if(this.cmb1.getSelectedIndex() == 2 && this.cmb2.getSelectedIndex() == 3) {
                        resultado = Double.parseDouble(this.velocidadField.getText()) / 1609;
                        this.result.setText(String.valueOf(resultado) + " mph");
                    } else if(this.cmb1.getSelectedIndex() == 3 && this.cmb2.getSelectedIndex() == 2) {
                        resultado = Double.parseDouble(this.velocidadField.getText()) * 1609;
                        this.result.setText(String.valueOf(resultado) + " km/h");
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_convertirBtnMouseClicked

    private void velocidadFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_velocidadFieldMouseClicked
        // TODO add your handling code here:
        this.velocidadField.setText("");
    }//GEN-LAST:event_velocidadFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorVelocidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorVelocidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorVelocidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorVelocidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorVelocidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> cmb1;
    public javax.swing.JComboBox<String> cmb2;
    private javax.swing.JPanel convertirBtn;
    private javax.swing.JLabel convertirTxt;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel result;
    private javax.swing.JTextField velocidadField;
    // End of variables declaration//GEN-END:variables
}
